#!/usr/bin/env python
import argparse
import os

try:
    from PIL import Image
except ImportError:
    Image = None


def create_ico(input_f, output_f):
    if Image is None:
        print('\nMust install Pillow!\n\n')
        return

    img = Image.open(input_f)
    img.save(output_f)
    print('\nSaved {} file.\n\n'.format(output_f))


parser = argparse.ArgumentParser(description='Icon generator.')
parser.add_argument('--input', '-i', type=str, required=True,
                    help='Input file for conversion, required.')
parser.add_argument('--output', '-o', type=str, default='favicon.ico',
                    help='Output filename, default "favicon.ico".')

args = parser.parse_args()

file_exists = os.path.exists(args.input)
if file_exists:
    create_ico(args.input, args.output)
else:
    print('\nFile {} does not exist!\n\n'.format(args.input))
